version: "1"

databases:
  - name: therabotdb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: TheraBotHutsy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Therabot.asgi:application -k uvicorn.workers.UvicornWorker --workers ${WEB_CONCURRENCY} --timeout 120 --keep-alive 5"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: therabotdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: HF_API_KEY
        value: your_huggingface_token_here  
      - key: DJANGO_SETTINGS_MODULE
        value: Therabot.settings.production 
